apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecrets.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogewogICAgICAgICJ1c2VybmFtZSI6ICJlc3BhZG9zIiwKICAgICAgICAicGFzc3dvcmQiOiAiRnpEQjEzRE0jRGZ6ZCIsCiAgICAgICAgImVtYWlsIjogInNhaWZ1bGxhaEBkaW4uZ2xvYmFsIiwKICAgICAgICAiYXV0aCI6ICJaWE53WVdSdmN6cEdla1JDTVRORVRTTkVabnBrIgogICAgICB9CiAgICB9CiAgfQogIA==
