apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello
  namespace: argo-cd
  labels:
    app-name: hello
spec:
  project: default
  source:
    repoURL: 'https://github.com/espados/helm.git'
    path: charts/hello
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../../clients/hello/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: hello
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
