apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}
  annotations:
    helm.sh/hook: post-install, post-upgrade
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  backoffLimit: 6
  template:
    spec:
      containers:
        - name: hello-world-job
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          env:
            - name: PRINT_MESSAGE
              value: {{ .Values.job.message | default "job" }}
      restartPolicy: Never
